server:
  port: 3101
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          #timeout: 4 # 配置超时
          #skip-ssl-validation: true # 关闭git服务器的ssl证书的验证
#          ignoreLocalSshSettings: true
          default-label: master
          force-pull: true
          uri: https://github.com/Only-TEL/workspace.git
          # 如果私有仓库，需要这里配置用户名和密码
          search-paths: foo,bar*,vue-demo  #Configserver会在 Git仓库根目录、 foo子目录，以及所有以 bar开始的子目录中查找配置文件。
          clone-on-start: true  #启动时就clone仓库到本地，默认是在配置被首次请求时，config server才会clone git仓库
        #native:
          #search-locations: classpath:/config #若配置中心在本地，本地的地址

# 进行服务注册
eureka:
  client:
    service-url:
      # ,http://eureka3002.top:3002/eureka,http://eureka3003.top:3003/eureka
      defaultZone: http://eureka3001.top:3001/eureka  # eureka服务端提供的注册地址