server:
  port: 6003
spring:
  application:
    name: module-order
# 进行服务注册
eureka:
  client:
    service-url:
      defaultZone: http://eureka3001.top:3001/eureka  # eureka服务端提供的注册地址
  instance:
    instance-id: module-order # 注册到eureka的应用程序的唯一标识
    prefer-ip-address: true  # 是否显示标识
    lease-renewal-interval-in-seconds: 5  # eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    lease-expiration-duration-in-seconds: 10 # eureka服务器在接受到应用实例的最后一次心跳后，需要等待多久才能将实例删除，在这个时间段内没有接受到心跳说明eureka就可以移除这个实例了

