spring:
  application:
    name: consumer # 配置应用名称
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://192.168.222.128:12181
server:
  port: 8081

# 配置服务的版本
demo:
  service:
    version: 1.1.1