spring:
  rabbitmq:
    host: 192.168.222.129
    port: 5672
    username: root
    password: root
    connection-timeout: 30000
    virtual-host: /kap
    listener:
      simple:
        # 开启手动确认消息
        acknowledge-mode: MANUAL
        # 消费者最小数量
        concurrency: 1
        # 消费者最大数量
        max-concurrency: 10
        # 在单个请求中处理的消息个数，他应该大于等于事务数量(unack的最大数量)
        prefetch: 2
